package br.com.portalmanager.platform.workspace.entrypoint.web.schema;
import br.com.portalmanager.platform.library.authorization.model.AuthorizationContext;
import br.com.portalmanager.platform.workspace.entrypoint.web.schema.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.schema.response.*;import br.com.portalmanager.platform.workspace.foundation.schema.facade.PlatformSchemaFacade;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/schemas") public class PlatformSchemaController {private final PlatformSchemaFacade facade;public PlatformSchemaController(PlatformSchemaFacade f){facade=f;}
@PostMapping public ResponseEntity<SchemaResponse> create(AuthorizationContext context, @RequestBody CreateSchemaRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(SchemaResponse.from(facade.create(context, r.toPlatformInput())));}
@GetMapping public List<SchemaResponse> findAll(AuthorizationContext context){return facade.findAll(context).stream().map(SchemaResponse::from).toList();}
@GetMapping("/{identifier}") public SchemaResponse findByIdentifier(AuthorizationContext context, @PathVariable String identifier){return SchemaResponse.from(facade.findByIdentifier(context, identifier));}
@PutMapping("/{identifier}") public SchemaResponse update(AuthorizationContext context, @PathVariable String identifier,@RequestBody UpdateSchemaRequest r){return SchemaResponse.from(facade.update(context, identifier,r.toInput()));}
@PatchMapping("/{identifier}/activate") public SchemaResponse activate(AuthorizationContext context, @PathVariable String identifier){return SchemaResponse.from(facade.activate(context, identifier));}
@PatchMapping("/{identifier}/inactivate") public SchemaResponse inactivate(AuthorizationContext context, @PathVariable String identifier){return SchemaResponse.from(facade.inactivate(context, identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> quarantine(AuthorizationContext context, @PathVariable String identifier){facade.quarantine(context, identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/versions") public ResponseEntity<SchemaVersionResponse> createVersion(AuthorizationContext context, @PathVariable String identifier,@RequestBody CreateSchemaVersionRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(SchemaVersionResponse.from(facade.createVersion(context, identifier,r.toInput())));}
@DeleteMapping("/{identifier}/versions/{versionIdentifier}") public ResponseEntity<Void> deleteDraft(AuthorizationContext context, @PathVariable String identifier,@PathVariable String versionIdentifier){facade.deleteDraft(context, identifier,versionIdentifier);return ResponseEntity.noContent().build();}
@GetMapping("/{identifier}/versions") public List<SchemaVersionResponse> findVersions(AuthorizationContext context, @PathVariable String identifier){return facade.findVersions(context, identifier).stream().map(SchemaVersionResponse::from).toList();}
@PatchMapping("/{identifier}/versions/{versionIdentifier}/publish") public SchemaVersionResponse publish(AuthorizationContext context, @PathVariable String identifier,@PathVariable String versionIdentifier){return SchemaVersionResponse.from(facade.publish(context, identifier,versionIdentifier));}}
