package br.com.portalmanager.platform.workspace.entrypoint.web.schema;
import br.com.portalmanager.platform.workspace.entrypoint.web.schema.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.schema.response.*;import br.com.portalmanager.platform.workspace.foundation.schema.facade.PlatformSchemaFacade;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/schemas") public class PlatformSchemaController {private final PlatformSchemaFacade facade;public PlatformSchemaController(PlatformSchemaFacade f){facade=f;}
@PostMapping public ResponseEntity<SchemaResponse> create(@RequestBody CreateSchemaRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(SchemaResponse.from(facade.create(r.toPlatformInput())));}
@GetMapping public List<SchemaResponse> findAll(){return facade.findAll().stream().map(SchemaResponse::from).toList();}
@GetMapping("/{identifier}") public SchemaResponse findByIdentifier(@PathVariable String identifier){return SchemaResponse.from(facade.findByIdentifier(identifier));}
@PutMapping("/{identifier}") public SchemaResponse update(@PathVariable String identifier,@RequestBody UpdateSchemaRequest r){return SchemaResponse.from(facade.update(identifier,r.toInput()));}
@PatchMapping("/{identifier}/activate") public SchemaResponse activate(@PathVariable String identifier){return SchemaResponse.from(facade.activate(identifier));}
@PatchMapping("/{identifier}/inactivate") public SchemaResponse inactivate(@PathVariable String identifier){return SchemaResponse.from(facade.inactivate(identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> quarantine(@PathVariable String identifier){facade.quarantine(identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/versions") public ResponseEntity<SchemaVersionResponse> createVersion(@PathVariable String identifier,@RequestBody CreateSchemaVersionRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(SchemaVersionResponse.from(facade.createVersion(identifier,r.toInput())));}
@DeleteMapping("/{identifier}/versions/{versionIdentifier}") public ResponseEntity<Void> deleteDraft(@PathVariable String identifier,@PathVariable String versionIdentifier){facade.deleteDraft(identifier,versionIdentifier);return ResponseEntity.noContent().build();}
@GetMapping("/{identifier}/versions") public List<SchemaVersionResponse> findVersions(@PathVariable String identifier){return facade.findVersions(identifier).stream().map(SchemaVersionResponse::from).toList();}
@PatchMapping("/{identifier}/versions/{versionIdentifier}/publish") public SchemaVersionResponse publish(@PathVariable String identifier,@PathVariable String versionIdentifier){return SchemaVersionResponse.from(facade.publish(identifier,versionIdentifier));}}
