package br.com.portalmanager.platform.workspace.entrypoint.web.schema;
import br.com.portalmanager.platform.workspace.entrypoint.web.schema.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.schema.response.SchemaConfigurationResponse;import br.com.portalmanager.platform.workspace.foundation.schema.facade.SchemaConfigurationFacade;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/schema-configurations") public class SchemaConfigurationController {private final SchemaConfigurationFacade facade;public SchemaConfigurationController(SchemaConfigurationFacade f){facade=f;}
@PostMapping public ResponseEntity<SchemaConfigurationResponse> create(@RequestBody CreateSchemaConfigurationRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(SchemaConfigurationResponse.from(facade.create(r==null?null:r.toInput())));}
@GetMapping public List<SchemaConfigurationResponse> findAll(){return facade.findAll().stream().map(SchemaConfigurationResponse::from).toList();}
@GetMapping("/{identifier}") public SchemaConfigurationResponse find(@PathVariable String identifier){return SchemaConfigurationResponse.from(facade.find(identifier));}
@PutMapping("/{identifier}") public SchemaConfigurationResponse update(@PathVariable String identifier,@RequestBody UpdateSchemaConfigurationRequest r){return SchemaConfigurationResponse.from(facade.update(identifier,r==null?null:r.toInput()));}
@PatchMapping("/{identifier}/activate") public SchemaConfigurationResponse activate(@PathVariable String identifier){return SchemaConfigurationResponse.from(facade.activate(identifier));}
@PatchMapping("/{identifier}/inactivate") public SchemaConfigurationResponse inactivate(@PathVariable String identifier){return SchemaConfigurationResponse.from(facade.inactivate(identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(@PathVariable String identifier){facade.delete(identifier);return ResponseEntity.noContent().build();}}
