package br.com.portalmanager.platform.workspace.entrypoint.web.environment;
import br.com.portalmanager.platform.library.authorization.model.AuthorizationContext;
import br.com.portalmanager.platform.workspace.core.environment.facade.DefaultEnvironmentFacade;import br.com.portalmanager.platform.workspace.entrypoint.web.environment.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.environment.response.EnvironmentResponse;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/environment-defaults") public class DefaultEnvironmentController {private final DefaultEnvironmentFacade facade;public DefaultEnvironmentController(DefaultEnvironmentFacade f){facade=f;}
@PostMapping public ResponseEntity<EnvironmentResponse> create(AuthorizationContext context, @RequestBody CreateEnvironmentRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(EnvironmentResponse.from(facade.create(context, r.toInput())));}
@GetMapping public List<EnvironmentResponse> list(AuthorizationContext context, @RequestParam(defaultValue="true") Boolean active){return facade.list(context, active).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/{identifier}") public EnvironmentResponse find(AuthorizationContext context, @PathVariable String identifier){return EnvironmentResponse.from(facade.find(context, identifier));}
@PutMapping("/{identifier}") public EnvironmentResponse update(AuthorizationContext context, @PathVariable String identifier,@RequestBody UpdateEnvironmentRequest r){return EnvironmentResponse.from(facade.update(context, identifier,r.toInput()));}
@PostMapping("/{identifier}/inactivate") public ResponseEntity<Void> inactivate(AuthorizationContext context, @PathVariable String identifier){facade.inactivate(context, identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/restore") public EnvironmentResponse restore(AuthorizationContext context, @PathVariable String identifier){return EnvironmentResponse.from(facade.restore(context, identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(AuthorizationContext context, @PathVariable String identifier){facade.delete(context, identifier);return ResponseEntity.noContent().build();}}
