package br.com.portalmanager.platform.workspace.entrypoint.web.environment;
import br.com.portalmanager.platform.workspace.core.environment.facade.WorkspaceEnvironmentFacade;import br.com.portalmanager.platform.workspace.entrypoint.web.environment.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.environment.response.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/workspaces/{workspaceIdentifier}/environments") public class WorkspaceEnvironmentController {private final WorkspaceEnvironmentFacade facade;public WorkspaceEnvironmentController(WorkspaceEnvironmentFacade f){facade=f;}
@PostMapping public ResponseEntity<EnvironmentResponse> create(@PathVariable String workspaceIdentifier,@RequestBody CreateEnvironmentRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(EnvironmentResponse.from(facade.create(workspaceIdentifier,r.toInput())));}
@GetMapping public List<EnvironmentResponse> list(@PathVariable String workspaceIdentifier,@RequestParam(defaultValue="true") Boolean active){return facade.list(workspaceIdentifier,active).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/{identifier}") public EnvironmentResponse find(@PathVariable String workspaceIdentifier,@PathVariable String identifier){return EnvironmentResponse.from(facade.find(workspaceIdentifier,identifier));}
@GetMapping("/roots") public List<EnvironmentResponse> roots(@PathVariable String workspaceIdentifier){return facade.roots(workspaceIdentifier).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/{identifier}/children") public List<EnvironmentResponse> children(@PathVariable String workspaceIdentifier,@PathVariable String identifier){return facade.children(workspaceIdentifier,identifier).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/tree") public List<EnvironmentTreeResponse> tree(@PathVariable String workspaceIdentifier){return facade.tree(workspaceIdentifier).stream().map(EnvironmentTreeResponse::from).toList();}
@PutMapping("/{identifier}") public EnvironmentResponse update(@PathVariable String workspaceIdentifier,@PathVariable String identifier,@RequestBody UpdateEnvironmentRequest r){return EnvironmentResponse.from(facade.update(workspaceIdentifier,identifier,r.toInput()));}
@PostMapping("/{identifier}/inactivate") public ResponseEntity<Void> inactivate(@PathVariable String workspaceIdentifier,@PathVariable String identifier){facade.inactivate(workspaceIdentifier,identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/restore") public EnvironmentResponse restore(@PathVariable String workspaceIdentifier,@PathVariable String identifier){return EnvironmentResponse.from(facade.restore(workspaceIdentifier,identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(@PathVariable String workspaceIdentifier,@PathVariable String identifier){facade.delete(workspaceIdentifier,identifier);return ResponseEntity.noContent().build();}}
