package br.com.portalmanager.platform.workspace.entrypoint.web.environment;
import br.com.portalmanager.platform.library.authorization.model.AuthorizationContext;
import br.com.portalmanager.platform.workspace.core.environment.facade.WorkspaceEnvironmentFacade;import br.com.portalmanager.platform.workspace.entrypoint.web.environment.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.environment.response.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/workspaces/{workspaceIdentifier}/environments") public class WorkspaceEnvironmentController {private final WorkspaceEnvironmentFacade facade;public WorkspaceEnvironmentController(WorkspaceEnvironmentFacade f){facade=f;}
@PostMapping public ResponseEntity<EnvironmentResponse> create(AuthorizationContext context, @PathVariable String workspaceIdentifier,@RequestBody CreateEnvironmentRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(EnvironmentResponse.from(facade.create(context, workspaceIdentifier,r.toInput())));}
@GetMapping public List<EnvironmentResponse> list(AuthorizationContext context, @PathVariable String workspaceIdentifier,@RequestParam(defaultValue="true") Boolean active){return facade.list(context, workspaceIdentifier,active).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/{identifier}") public EnvironmentResponse find(AuthorizationContext context, @PathVariable String workspaceIdentifier,@PathVariable String identifier){return EnvironmentResponse.from(facade.find(context, workspaceIdentifier,identifier));}
@GetMapping("/roots") public List<EnvironmentResponse> roots(AuthorizationContext context, @PathVariable String workspaceIdentifier){return facade.roots(context, workspaceIdentifier).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/{identifier}/children") public List<EnvironmentResponse> children(AuthorizationContext context, @PathVariable String workspaceIdentifier,@PathVariable String identifier){return facade.children(context, workspaceIdentifier,identifier).stream().map(EnvironmentResponse::from).toList();}
@GetMapping("/tree") public List<EnvironmentTreeResponse> tree(AuthorizationContext context, @PathVariable String workspaceIdentifier){return facade.tree(context, workspaceIdentifier).stream().map(EnvironmentTreeResponse::from).toList();}
@PutMapping("/{identifier}") public EnvironmentResponse update(AuthorizationContext context, @PathVariable String workspaceIdentifier,@PathVariable String identifier,@RequestBody UpdateEnvironmentRequest r){return EnvironmentResponse.from(facade.update(context, workspaceIdentifier,identifier,r.toInput()));}
@PostMapping("/{identifier}/inactivate") public ResponseEntity<Void> inactivate(AuthorizationContext context, @PathVariable String workspaceIdentifier,@PathVariable String identifier){facade.inactivate(context, workspaceIdentifier,identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/restore") public EnvironmentResponse restore(AuthorizationContext context, @PathVariable String workspaceIdentifier,@PathVariable String identifier){return EnvironmentResponse.from(facade.restore(context, workspaceIdentifier,identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(AuthorizationContext context, @PathVariable String workspaceIdentifier,@PathVariable String identifier){facade.delete(context, workspaceIdentifier,identifier);return ResponseEntity.noContent().build();}}
