package br.com.portalmanager.platform.workspace.foundation.schema.facade;
import br.com.portalmanager.platform.library.authorization.annotation.AuthorizationRequired;import br.com.portalmanager.platform.library.authorization.model.*;import br.com.portalmanager.platform.workspace.foundation.schema.usecase.model.*;import br.com.portalmanager.platform.workspace.foundation.schema.usecase.operations.schema.*;import br.com.portalmanager.platform.workspace.foundation.schema.usecase.operations.version.SchemaVersionCommandService;import org.springframework.stereotype.Service;import java.util.List;
@Service public class PlatformSchemaFacade {private final SchemaCommandService commandService;private final SchemaQueryService queryService;private final SchemaVersionCommandService versionCommandService;public PlatformSchemaFacade(SchemaCommandService c,SchemaQueryService q,SchemaVersionCommandService v){commandService=c;queryService=q;versionCommandService=v;}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.CREATE) public SchemaOutput create(CreateSchemaInput i){return commandService.createPlatform(i);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.READ) public List<SchemaOutput> findAll(){return queryService.findPlatform();}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.READ) public SchemaOutput findByIdentifier(String i){return queryService.findPlatformByIdentifier(i);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.UPDATE) public SchemaOutput update(String i,UpdateSchemaInput in){return commandService.updatePlatform(i,in);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.ACTIVATE) public SchemaOutput activate(String i){return commandService.activatePlatform(i);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.DEACTIVATE) public SchemaOutput inactivate(String i){return commandService.inactivatePlatform(i);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.DELETE) public void quarantine(String i){commandService.quarantinePlatform(i);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.CREATE) public SchemaVersionOutput createVersion(String i,CreateSchemaVersionInput in){return versionCommandService.createPlatformDraft(i,in);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.DELETE) public void deleteDraft(String i,String v){versionCommandService.deletePlatformDraft(i,v);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.READ) public List<SchemaVersionOutput> findVersions(String i){return queryService.findPlatformVersions(i);}
@AuthorizationRequired(level=AuthorizationLevel.OWNER,action=AuthorizationAction.UPDATE) public SchemaVersionOutput publish(String i,String v){return versionCommandService.publishPlatform(i,v);}}
