spring:
  application:
    name: workspace-service
  main:
    banner-mode: "off"
  datasource:
    url: ${WORKSPACE_DB_URL:jdbc:mysql://localhost:3306/workspace_db}
    username: ${WORKSPACE_DB_USERNAME:workspace}
    password: ${WORKSPACE_DB_PASSWORD:workspace}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

platform:
  observability:
    logging:
      levels:
        br.com.portalmanager.platform.workspace: DEBUG
        br.com.portalmanager.platform: DEBUG
  authorization:
    mode: ${PLATFORM_AUTHORIZATION_MODE:REAL}
    service-url: ${AUTHORIZATION_SERVICE_URL:http://localhost:2020}
    mock:
      user-name: bbs
      email: bruno.barbosa@empresa.com.br

      account-id: '-'
      application-id: '-'
      environment-id: '-'

      trace-id: '81f3503a-8153-4b80-9ee8-5ef41e611b31'

      groups:
        - PM5_OWNER

  messaging:
    enabled: true
    default-locale: pt-BR
    datasource:
      enabled: true
      view-name: vw_platform_messages
    cache:
      enabled: false
  schema-validation:
    enabled: true
    fallback-code: DEFAULT
    datasource:
      enabled: true
      view-name: vw_platform_resource_schemas
  audit:
    enabled: ${AUDIT_ENABLED:true}
    service-name: workspace-service
