package br.com.portalmanager.platform.workspace.entrypoint.web.platform.feature;
import br.com.portalmanager.platform.workspace.entrypoint.web.platform.context.response.FeatureContextResponse;import br.com.portalmanager.platform.workspace.entrypoint.web.platform.feature.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.platform.feature.response.FeatureResponse;import br.com.portalmanager.platform.workspace.feature.platform.facade.FeatureFacade;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/platform/features") public class FeatureController {private final FeatureFacade facade;public FeatureController(FeatureFacade f){facade=f;}
@PostMapping public ResponseEntity<FeatureResponse> create(@RequestBody CreateFeatureRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(FeatureResponse.from(facade.create(r.toInput())));}
@GetMapping("/{identifier}") public FeatureResponse findByIdentifier(@PathVariable String identifier){return FeatureResponse.from(facade.findByIdentifier(identifier));}
@GetMapping public List<FeatureResponse> findAll(@RequestParam(required=false) String contextCode){return facade.findAll(contextCode).stream().map(FeatureResponse::from).toList();}
@GetMapping("/{identifier}/contexts") public List<FeatureContextResponse> findContexts(@PathVariable String identifier){return facade.findContexts(identifier).stream().map(FeatureContextResponse::from).toList();}
@PutMapping("/{identifier}") public FeatureResponse update(@PathVariable String identifier,@RequestBody UpdateFeatureRequest r){return FeatureResponse.from(facade.update(identifier,r.toInput()));}
@PatchMapping("/{identifier}/activate") public FeatureResponse activate(@PathVariable String identifier){return FeatureResponse.from(facade.activate(identifier));}
@PatchMapping("/{identifier}/inactivate") public FeatureResponse inactivate(@PathVariable String identifier){return FeatureResponse.from(facade.inactivate(identifier));}
@PostMapping("/{identifier}/contexts/{contextIdentifier}") public FeatureResponse associateContext(@PathVariable String identifier,@PathVariable String contextIdentifier){return FeatureResponse.from(facade.associateContext(identifier,contextIdentifier));}
@DeleteMapping("/{identifier}/contexts/{contextIdentifier}") public FeatureResponse removeContext(@PathVariable String identifier,@PathVariable String contextIdentifier){return FeatureResponse.from(facade.removeContext(identifier,contextIdentifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(@PathVariable String identifier){facade.delete(identifier);return ResponseEntity.noContent().build();}}
