package br.com.portalmanager.platform.workspace.entrypoint.web.workspace;
import br.com.portalmanager.platform.workspace.core.workspace.facade.WorkspaceFacade;import br.com.portalmanager.platform.workspace.entrypoint.web.workspace.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.workspace.response.WorkspaceResponse;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/workspaces") public class WorkspaceController {private final WorkspaceFacade facade;public WorkspaceController(WorkspaceFacade f){facade=f;}
@PostMapping public ResponseEntity<WorkspaceResponse> create(@RequestBody CreateWorkspaceRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(WorkspaceResponse.from(facade.create(r.toInput())));}
@GetMapping("/{identifier}") public WorkspaceResponse findByIdentifier(@PathVariable String identifier){return WorkspaceResponse.from(facade.findByIdentifier(identifier));}
@GetMapping public List<WorkspaceResponse> findAll(@RequestParam(defaultValue="true") Boolean active,@RequestParam(required=false) String typeName,@RequestParam(required=false) String tagName){return facade.findAll(active,typeName,tagName).stream().map(WorkspaceResponse::from).toList();}
@PutMapping("/{identifier}") public WorkspaceResponse update(@PathVariable String identifier,@RequestBody UpdateWorkspaceRequest r){return WorkspaceResponse.from(facade.update(identifier,r.toInput()));}
@PostMapping("/{identifier}/inactivate") public ResponseEntity<Void> inactivate(@PathVariable String identifier){facade.inactivate(identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/restore") public WorkspaceResponse restore(@PathVariable String identifier){return WorkspaceResponse.from(facade.restore(identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(@PathVariable String identifier){facade.delete(identifier);return ResponseEntity.noContent().build();}}
