package br.com.portalmanager.platform.workspace.entrypoint.web.publisher;
import br.com.portalmanager.platform.library.authorization.model.AuthorizationContext;
import br.com.portalmanager.platform.workspace.core.publisher.facade.PublisherFacade;import br.com.portalmanager.platform.workspace.entrypoint.web.publisher.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.publisher.response.PublisherResponse;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/publishers") public class PublisherController {private final PublisherFacade facade;public PublisherController(PublisherFacade f){facade=f;}
@PostMapping public ResponseEntity<PublisherResponse> create(AuthorizationContext context, @RequestBody CreatePublisherRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(PublisherResponse.from(facade.create(context, r.toInput())));}
@GetMapping public List<PublisherResponse> list(AuthorizationContext context, @RequestParam(defaultValue="true") Boolean active,@RequestParam(required=false) String scope){return facade.list(context, active,scope).stream().map(PublisherResponse::from).toList();}
@GetMapping("/{identifier}") public PublisherResponse find(AuthorizationContext context, @PathVariable String identifier){return PublisherResponse.from(facade.find(context, identifier));}
@PutMapping("/{identifier}") public PublisherResponse update(AuthorizationContext context, @PathVariable String identifier,@RequestBody UpdatePublisherRequest r){return PublisherResponse.from(facade.update(context, identifier,r.toInput()));}
@PostMapping("/{identifier}/inactivate") public ResponseEntity<Void> inactivate(AuthorizationContext context, @PathVariable String identifier){facade.inactivate(context, identifier);return ResponseEntity.noContent().build();}
@PostMapping("/{identifier}/restore") public PublisherResponse restore(AuthorizationContext context, @PathVariable String identifier){return PublisherResponse.from(facade.restore(context, identifier));}
@DeleteMapping("/{identifier}") public ResponseEntity<Void> delete(AuthorizationContext context, @PathVariable String identifier){facade.delete(context, identifier);return ResponseEntity.noContent().build();}}
