package br.com.portalmanager.platform.workspace.entrypoint.web.message;
import br.com.portalmanager.platform.workspace.entrypoint.web.message.request.*;import br.com.portalmanager.platform.workspace.entrypoint.web.message.response.MessageTranslationResponse;import br.com.portalmanager.platform.workspace.feature.message.facade.MessageTranslationFacade;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/messages/{messageIdentifier}/translations") public class MessageTranslationController {private final MessageTranslationFacade facade;public MessageTranslationController(MessageTranslationFacade f){facade=f;}
@GetMapping public List<MessageTranslationResponse> findAll(@PathVariable String messageIdentifier,@RequestParam(required=false) String locale,@RequestParam(required=false) Boolean active){return facade.findAll(messageIdentifier,locale,active).stream().map(MessageTranslationResponse::from).toList();}
@GetMapping("/{translationIdentifier}") public MessageTranslationResponse findByIdentifier(@PathVariable String messageIdentifier,@PathVariable String translationIdentifier){return MessageTranslationResponse.from(facade.findByIdentifier(messageIdentifier,translationIdentifier));}
@PostMapping public ResponseEntity<MessageTranslationResponse> create(@PathVariable String messageIdentifier,@RequestBody CreateMessageTranslationRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(MessageTranslationResponse.from(facade.create(messageIdentifier,r.toInput())));}
@PutMapping("/{translationIdentifier}") public MessageTranslationResponse update(@PathVariable String messageIdentifier,@PathVariable String translationIdentifier,@RequestBody UpdateMessageTranslationRequest r){return MessageTranslationResponse.from(facade.update(messageIdentifier,translationIdentifier,r.toInput()));}
@PatchMapping("/{translationIdentifier}/activate") public MessageTranslationResponse activate(@PathVariable String messageIdentifier,@PathVariable String translationIdentifier){return MessageTranslationResponse.from(facade.activate(messageIdentifier,translationIdentifier));}
@PatchMapping("/{translationIdentifier}/inactivate") public MessageTranslationResponse inactivate(@PathVariable String messageIdentifier,@PathVariable String translationIdentifier){return MessageTranslationResponse.from(facade.inactivate(messageIdentifier,translationIdentifier));}
@DeleteMapping("/{translationIdentifier}") public ResponseEntity<Void> delete(@PathVariable String messageIdentifier,@PathVariable String translationIdentifier){facade.delete(messageIdentifier,translationIdentifier);return ResponseEntity.noContent().build();}}
